[package]
name = "gitix"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29", features = ["widget-calendar"] }
crossterm = "0.29"
gix = "0.72.1"
chrono = "0.4"
time = "0.3"
